# Generated by Django 5.1.7 on 2025-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loisirs',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
